/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorldLib: typeof import('./src/components/HelloWorldLib.vue')['default']
    HelloWorldLib2: typeof import('./src/components/HelloWorldLib2.vue')['default']
  }
}
