version: "3.6"
services:
  bonomo3:
    image: node:20-alpine
#    build:
#      context: .
    working_dir: /app/
    entrypoint: /bin/ash
    ports:
#      - 6006:6006
      - 6007:6007
    volumes:
      - .:/app/
    tty: true
