version: "3.6"
services:
  bonomo3:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: vue-vuetify-boilerplate
    ports:
      - 3000:3000
    tty: true
    volumes:
      - .:/app/
    working_dir: /app/
