FROM node:20-alpine

WORKDIR /app

COPY ["package.json", "package-lock.json", "./"]
COPY ["./dependencies/*" , "./dependencies/"]

RUN npm ci

COPY . .

RUN npm run build

CMD [ "npm", "run", "dev" ]
